version: 0.2

phases:
  pre_build:
    commands:
      - echo "Validating environment variables..."
      - echo "AWS_REGION=$AWS_REGION"
      - echo "AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID"
      - echo "ECR_REPO_NAME=$ECR_REPO_NAME"
      - echo "AUTH_TYPE=$AUTH_TYPE"
      - echo "SERVER=$SERVER"
      - echo "Authenticating to GitHub..."
      - echo "Authenticating to Docker Hub..."
      - echo "$DOCKERTOKEN" | docker login --username "$DOCKERUSERNAME" --password-stdin
      - git config --global user.name "$(GITHUB_OWNER)"
      - git config --global user.email "$(GITHUB_OWNER)@users.noreply.github.com"
      - git clone https://${AUTH_TYPE}:${GITHUB_TOKEN}@github.com/${GITHUB_OWNER}/${GITHUB_REPO}.git repo
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - cd repo

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $ECR_REPO_NAME .
      - docker tag $ECR_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:latest
      - echo "Docker image pushed successfully!"
      - echo "Generating imagedefinitions.json..."
      - echo '[{"name":"fastapi-container","imageUri":"'$AWS_ACCOUNT_ID'.dkr.ecr.'$AWS_REGION'.amazonaws.com/'$ECR_REPO_NAME':latest"}]' > imagedefinitions.json
      - cat imagedefinitions.json      

env:
  variables:
    AWS_REGION: "us-east-1"
    AWS_ACCOUNT_ID: "475634715655"
    AUTH_TYPE: "PERSONAL_ACCESS_TOKEN"
    SERVER: "GitHub"

artifacts:
  files:
    - imagedefinitions.json
