version: 0.2
phases:
  pre_build:
    commands:
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region $(AWS_REGION) | docker login --username AWS --password-stdin $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t fastapi-app .
      - docker tag fastapi-app:latest $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/fastapi-app:latest
  post_build:
    commands:
      - echo "Pushing the Docker image..."
      - docker push $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/fastapi-app:latest
      - echo "Writing image definitions file..."
      - echo '[{"name":"fastapi-container","imageUri":"$(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/fastapi-app:latest"}]' > $(IMAGEDef_FILE)

