version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    AWS_ACCOUNT_ID: "475634715655"
    ECR_REPO_NAME: "fastapi-app"

phases:
  pre_build:
      commands:
      - echo "Testing GitHub access with OAuth token..."
      - curl -H "Authorization: token $GITHUB_OAUTH_TOKEN" https://api.github.com/repos/$GITHUB_OWNER/$GITHUB_REPO || exit 1
      - echo "Authenticating with GitHub..."
      - git clone https://$GITHUB_OAUTH_TOKEN@github.com/$GITHUB_OWNER/$GITHUB_REPO.git repo
      - cd repo
      
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $ECR_REPO_NAME .
      - docker tag $ECR_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:latest
  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:latest
      - echo "Docker image pushed successfully!"
