AWSTemplateFormatVersion: '2010-09-09'
Description: "IAM roles for CodePipeline and CodeBuild."

Parameters:
  SecretArn:
    Type: String
    Description: "ARN of the first secret for CodeBuild to access"

Resources:
  CodePipelineRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "codepipeline.amazonaws.com"
                - "codebuild.amazonaws.com"
                - "ecs-tasks.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSCodePipeline_FullAccess"
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - "arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess"
        - "arn:aws:iam::aws:policy/AmazonECS_FullAccess"
        - "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"
        - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy" 
        - "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
      Policies:
        - PolicyName: AllowCustomPolicies
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "secretsmanager:GetSecretValue"
                  - "secretsmanager:DescribeSecret"
                  - "secretsmanager:ListSecrets"
                Resource:
                  - !Ref SecretArn
              - Effect: Allow
                Action:
                  - "iam:PassRole"
                Resource: "*"
        - PolicyName: AllowECRAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ecr:GetAuthorizationToken"
                  - "ecr:BatchGetImage"
                  - "ecr:GetDownloadUrlForLayer"
                  - "ecr:DescribeRepositories"
                  - "ecr:PutImage"
                  - "ecr:BatchCheckLayerAvailability"
                  - "ecr:InitiateLayerUpload"
                  - "ecr:UploadLayerPart"
                  - "ecr:CompleteLayerUpload"
                Resource: "*"
        - PolicyName: AllowCodeBuild
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "codebuild:StartBuild"
                  - "codebuild:BatchGetBuilds"
                Resource: "*"
        - PolicyName: AllowECSExecutionRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ecs:RunTask"
                  - "ecs:UpdateService"
                  - "ecs:DescribeServices"
                  - "ecs:DescribeTaskDefinition"
                  - "ecs:ListTasks"
                  - "ecs:StopTask"
                  - "ecs:DescribeTasks"
                  - "ecs:ListTaskDefinitions"
                  - "ecs:RegisterTaskDefinition"
                  - "ecs:DeregisterTaskDefinition"
                  - "ecs:TagResource"
                  - "ecs:UntagResource"
                Resource: "*"
        - PolicyName: AllowPipelineS3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"                  
                  - "s3:ListBucket"
                  - "s3:GetBucketLocation"                  
                Resource: "arn:aws:s3:::*"
                Condition:
                  StringLike:
                    "s3:prefix": "*codepipeline-artifacts-*"


      Tags:
        - Key: Environment
          Value: Production
        - Key: ProjectName
          Value: FastAPI-Pipeline
      

Outputs:
  CodePipelineRoleArn:
    Description: "The ARN of the CodePipeline IAM Role"
    Value: !GetAtt CodePipelineRole.Arn
    Export:
      Name: CodePipelineRoleArn


