AWSTemplateFormatVersion: '2010-09-09'
Description: "IAM roles for CodePipeline and CodeBuild."

Parameters:
  AWSSECRETS:
    Type: String
    Description: "Name of the AWS Secrets Manager resource"

Parameters:
  SecretArns:
    Type: CommaDelimitedList
    Description: "List of secret ARNs for CodeBuild to access"

Resources:
  CodePipelineRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "codepipeline.amazonaws.com"
                - "codebuild.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSCodePipeline_FullAccess"
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - "arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess"
        - "arn:aws:iam::aws:policy/AmazonECS_FullAccess"
        - "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"
      Policies:
        - PolicyName: AllowCustomPolicies
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "secretsmanager:GetSecretValue"
                  - "secretsmanager:DescribeSecret"
                Resource: !Split [",", !Ref SecretArns]
              - Effect: Allow
                Action:
                  - "iam:PassRole"
                Resource: "*"
        - PolicyName: AllowECRAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ecr:GetAuthorizationToken"
                  - "ecr:BatchGetImage"
                  - "ecr:GetDownloadUrlForLayer"
                  - "ecr:DescribeRepositories"
                Resource: "*"
      Tags:
        - Key: Environment
          Value: Production
        - Key: ProjectName
          Value: FastAPI-Pipeline

Outputs:
  RoleArn:
    Description: "ARN of the CodePipeline IAM Role"
    Value: !GetAtt CodePipelineRole.Arn


