AWSTemplateFormatVersion: '2010-09-09'
Description: "CloudFormation template for FastAPI ECS pipeline setup with CodePipeline and CodeBuild."

Parameters:
  GitHubOwner:
    Type: String
    Description: "GitHub repository owner"
  GitHubRepo:
    Type: String
    Description: "GitHub repository name"
  AWSRegion:
    Type: String
    Default: "us-east-1"
    Description: "AWS Region"
  RepositoryName:
    Type: String
    Default: "fastapi-app"
    Description: "ECR Repository Name"
  ClusterName:
    Type: String
    Default: "FastAPICluster"
    Description: "ECS Cluster Name"
  TaskFamily:
    Type: String
    Default: "fastapi-task"
    Description: "ECS Task Definition Family"
  ContainerName:
    Type: String
    Default: "fastapi-container"
    Description: "ECS Container Name"
  SubnetIds:
    Type: CommaDelimitedList
    Description: "List of Subnet IDs for ECS tasks"
  ProjectName:
    Type: String
    Default: "FastAPIBuildProject"
    Description: "CodeBuild Project Name"
  ConnectionArn:
    Type: String
    Description: "CodeStar Connection ARN for GitHub integration"

Conditions:
  ECRNotExists: !Equals [!Ref RepositoryName, ""]

Resources:

  # Github connection  
  GitHubConnection:
  Type: AWS::CodeStarConnections::Connection
  Properties:
    ConnectionName: GitHubConnection
    ProviderType: GitHub

  # ECR Repository
  ECRRepository:
    Condition: ECRNotExists
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: !Ref RepositoryName

  # ECS Cluster
  ECSCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: !Ref ClusterName

  # ECS Task Definition
  ECSTaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      Family: !Ref TaskFamily
      Cpu: "256"
      Memory: "512"
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt ECSExecutionRole.Arn
      ContainerDefinitions:
        - Name: !Ref ContainerName
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${RepositoryName}:latest"
          Memory: 512
          Cpu: 256
          PortMappings:
            - ContainerPort: 8000
            
  CodePipelineRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - "codepipeline.amazonaws.com"
                - "codebuild.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSCodePipeline_FullAccess"
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - "arn:aws:iam::aws:policy/AWSCodeBuildAdminAccess"
        - "arn:aws:iam::aws:policy/AmazonECS_FullAccess"
        - "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"
      Policies:
        - PolicyName: AllowCustomPolicies
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "secretsmanager:GetSecretValue"
                  - "secretsmanager:DescribeSecret"
                Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret/${AWSSECRETS}*"
        - PolicyName: AllowCodeStarConnection
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "codestar-connections:UseConnection"
                Resource: !GetAtt GitHubCodeStarConnection.ConnectionArn


  ECSExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "ecs-tasks.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"

  # ECS Service
  ECSService:
    Type: "AWS::ECS::Service"
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      TaskDefinition: !Ref ECSTaskDefinition
      LaunchType: "FARGATE"
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: !Ref SubnetIds
          AssignPublicIp: "ENABLED"


  # CodeBuild Project
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ProjectName
      Source:
        Type: CODESTAR
        Location: !GetAtt GitHubCodeStarConnection.ConnectionArn
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      ServiceRole: !GetAtt CodePipelineRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS

  # CodePipeline
CodePipeline:
  Type: "AWS::CodePipeline::Pipeline"
  Properties:
    RoleArn: !GetAtt CodePipelineRole.Arn
    ArtifactStore:
      Type: S3
      Location: !Sub "${AWS::AccountId}-codepipeline-artifacts-${AWS::Region}"
    Stages:
      - Name: "Source"
        Actions:
          - Name: "Source"
            ActionTypeId:
              Category: "Source"
              Owner: AWS
              Provider: CodeStarSourceConnection
              Version: "1"
            Configuration:
              ConnectionArn: !Ref ConnectionArn
              FullRepositoryId: !Sub "${GitHubOwner}/${GitHubRepo}"
              BranchName: "main"
            OutputArtifacts:
              - Name: "SourceOutput"
      - Name: "Build"
        Actions:
          - Name: "Build"
            ActionTypeId:
              Category: "Build"
              Owner: "AWS"
              Provider: "CodeBuild"
              Version: "1"
            InputArtifacts:
              - Name: "SourceOutput"
            OutputArtifacts:
              - Name: "BuildOutput"
            Configuration:
              ProjectName: !Ref ProjectName
      - Name: "Deploy"
        Actions:
          - Name: "Deploy"
            ActionTypeId:
              Category: "Deploy"
              Owner: "AWS"
              Provider: "ECS"
              Version: "1"
            InputArtifacts:
              - Name: "BuildOutput"
            Configuration:
              ClusterName: !Ref ECSCluster
              ServiceName: !Ref ECSService
              FileName: "imagedefinitions.json"

Outputs:
  PipelineName:
    Description: "The name of the CodePipeline"
    Value: !Ref CodePipeline
  ClusterName:
    Description: "The name of the ECS Cluster"
    Value: !Ref ECSCluster
  TaskDefinition:
    Description: "The ECS Task Definition"
    Value: !Ref ECSTaskDefinition
